// Entry point for the build script in your package.json
import "./main"
import "aos"
import "boxicons"
import "typed"
import "swiper"
import "isotope-layout"
import "glightbox"
import "@hotwired/turbo-rails"
import "./controllers"
import * as bootstrap from "bootstrap"
